package com.ysdc.aidpdf.tracking

object TrackingEventNames {
    const val INSTALL = "install"
    const val LOADING_VIEW = "loading_view"
    const val SESSION = "session"
    const val SESSION_BACK = "session_back"
    const val USER_BUY = "user_buy"
    const val USER_REFERRER = "user_referrer"
    const val USER_REVIEW = "user_review"
    const val USE_TEST_ADS = "use_testads"
    const val USE_EMULATOR = "use_emulator"
    const val USE_NO_SIM = "use_nosim"
    const val USE_ADB = "use_adb"

    const val SYSTEM_NOTIFICATION_POPUP_VIEW = "system_notification_popup_view"
    const val CUSTOM_NOTIFICATION_POPUP_VIEW = "customize_notification_popup_view"
    const val CUSTOM_NOTIFICATION_POPUP_PASS = "customize_notification_popup_pass"
    const val CUSTOM_NOTIFICATION_POPUP_SKIP = "customize_notification_popup_skip"
    const val SYSTEM_NOTIFICATION_ALLOW = "system_notification_allow"
    const val FLOATING_NOTIFICATION_POPUP_VIEW = "floating_notification_popup_view"
    const val FLOATING_NOTIFICATION_POPUP_PASS = "floating_notification_popup_pass"
    const val FLOATING_NOTIFICATION_POPUP_SKIP = "floating_notification_popup_skip"
    const val FLOATING_NOTIFICATION_ALLOW = "floating_notification_allow"

//    const val SHIELD_DETECTION_PASS = "shield_detection_pass"
//    const val PERIOD_DETECTION_PASS = "period_detection_pass"
//    const val SWITCH_DETECTION_PASS = "switch_detection_pass"
//    const val BACK_DETECTION_PASS = "back_detection_pass"
//    const val INTERVAL_DETECTION_PASS = "interval_detection_pass"
//    const val DAILY_DETECTION_PASS = "daily_detection_pass"
//    const val TRIGGER_NOTIFICATION_SUCCESS = "trigger_notification_success"
    const val SYSTEM_NOTIFICATION_TRIGGER = "system_notification_trigger"
    const val SYSTEM_NOTIFICATION_CLICK = "system_notification_click"
    const val FLOATING_NOTIFICATION_TRIGGER = "floating_notification_trigger"
    const val FLOATING_NOTIFICATION_VIEW = "floating_notification_view"
    const val FLOATING_NOTIFICATION_CLICK = "floating_notification_click"
    const val MEDIA_NOTIFICATION_TRIGGER = "media_notification_trigger"
    const val MEDIA_NOTIFICATION_CLICK = "media_notification_click"
    const val MEDIA2_NOTIFICATION_CLICK = "media2_notification_click"
    const val ALWAYS_NOTIFICATION_TRIGGER = "always_notification_trigger"
    const val ALWAYS_NOTIFICATION_CLICK = "always_notification_click"
//    const val TIME_SCENE_SEND = "time_scene_send"
//    const val UNLOCK_SCENE_SEND = "unlock_scene_send"
//    const val ALARM_SCENE_SEND = "alarm_scene_send"
//    const val HOME_SCENE_SEND = "home_scene_send"
//    const val EXIT_SCENE_SEND = "exit_scene_send"
//    const val RECENT_SCENE_SEND = "recent_scene_send"
//    const val AD_CLICK_SCENE_SEND = "adclick_scene_send"

    const val AD_PLACEMENT_REQUEST = "Shark_ad_placement_request"
    const val AD_SOURCE_REQUEST = "Shark_ad_source_request"
    const val AD_SOURCE_ERROR = "Shark_ad_source_error"
    const val AD_CHANCE = "Shark_ad_chance"
    const val AD_IMPRESSION = "Shark_ad_impression"
    const val AD_IMPRESSION_ERROR = "Shark_ad_impression_error"
    const val ADMOB_IMPRESSION = "ad_impression"
    const val AD_CLICK = "Shark_ad_click"
    const val AD_CLOSE = "Shark_ad_close"
    const val AD_IMPRESSION_REVENUE = "ad_impression_revenue"

    const val HOMEPAGE_VIEW = "hompage_view"
    const val USER_VPN = "user_vpn"
}
